"""Security headers middleware for the nyaya ASGI app.

Sets standard security headers on every HTTP response:
- Content-Security-Policy: restricts all resource loading to same-origin.
- X-Frame-Options: DENY (clickjacking protection).
- X-Content-Type-Options: nosniff (MIME-sniffing protection).
- Referrer-Policy: strict-origin-when-cross-origin.
- Permissions-Policy: denies camera, microphone, geolocation.
- Strict-Transport-Security: HSTS (only over HTTPS).

This is the single source of truth for the static-export Next.js SPA served
from the same origin — the build artifact doesn't need its own ``_headers``
file.

Pure-ASGI implementation (no ``BaseHTTPMiddleware``): it wraps ``send`` and
stamps headers onto ``http.response.start``, so it neither spawns the
per-request response task nor buffers streaming bodies — safe for SSE.
"""

from __future__ import annotations

from starlette.datastructures import MutableHeaders
from starlette.types import ASGIApp, Message, Receive, Scope, Send

# 'unsafe-inline' is allowed because Next.js injects runtime styles and
# hydration scripts. Tighten in the future by switching to nonce-based CSP.
_CSP = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline'; "
    "style-src 'self' 'unsafe-inline'; "
    "img-src 'self' data:; "
    "font-src 'self'; "
    "connect-src 'self'; "
    "frame-ancestors 'none'; "
    "base-uri 'self'; "
    "form-action 'self'"
)

_SECURITY_HEADERS = {
    "Content-Security-Policy": _CSP,
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
}


class SecurityHeadersMiddleware:
    """Add security headers to every response (pure ASGI).

    Lives near the outside of the stack (below CORS) so security headers are
    stamped even on error/limit responses generated by inner middleware
    (429 rate-limit, 413 body-cap, 503 degraded). ``setdefault`` preserves
    any header an inner layer set explicitly.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        async def send_with_headers(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                for key, value in _SECURITY_HEADERS.items():
                    headers.setdefault(key, value)
                # HSTS only over HTTPS. Behind a reverse proxy, scope["scheme"]
                # reflects the original protocol via X-Forwarded-Proto.
                if scope.get("scheme") == "https":
                    headers.setdefault(
                        "Strict-Transport-Security",
                        "max-age=31536000; includeSubDomains",
                    )
            await send(message)

        await self.app(scope, receive, send_with_headers)
